name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push-images:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: docker build api
      run: |
        docker build ./WebAPI -t ${{ secrets.DOCKERHUB_USERNAME }}/webapi:latest
    -
      name: docker build app
      run: |
        docker build ./WebApp -t ${{ secrets.DOCKERHUB_USERNAME }}/webapp:latest
    -
      name: docker push images
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/webapi:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/webapp:latest
        

deploy:

  needs: [build-and-push-image]
  runs-on: ubuntu-latest
  steps:
  -
    # Install SSH key for deployment to Linux server
    name: Install SSH key
    uses: webfactory/ssh-agent@v0.5.0
    with:
      ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  -
    # checking and see the deploy file
    name: cat deploy file
    run: |
      ssh ${{ secrets.USER }}@${{ secrets.IP }} "cd /home/ubuntu/ICO-DAT/src && cat deploy.sh"
  
